# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vunb.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Bao-Vu's blog"
  avatar: # avatar.png
  gravatar: 7fff53678ddafc5f1652a5f7e5d04c17 # Email MD5 hash
  description: "Bao-Vu's blog on Github." # used by search engines

  # Header and footer text
  header_text: >
     <h3>NLP = Text + Voice</h3>
  header_text_feature_image:
  footer_text: >
   Written with <i class="fa fa-heart orange" aria-hidden="true"></i> by Bao-Vu Nhu.

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "vunb"
  google_plus:
  instagram:
  linkedin: # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "nhubaovu"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-48010057-5" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "vunb"
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Xem chi tiết"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate, jekyll-sitemap]
